---
version: '3.4'
services:
  storagenode:
    image: storjlabs/storagenode:beta
    container_name: storagenode 
    hostname: storagenode 
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev/rtc:/dev/rtc:ro
      - /opt/appdata/storj/identity/storagenode:/app/identity
      - /opt/appdata/storj/storagenode:/app/config
    env_file:
      - storj.env
    ports:
      - 28967:28967
      - 14002:14002
  
  openvpn:
    cap_add:
     - NET_ADMIN
    image: evolvedm/openvpn-rpi
    container_name: openvpn
    hostname: openvpn
    ports:
     - "28967:1194/udp"
    restart: always
    volumes:
     - /opt/appdata/openvpn:/etc/openvpn
     - /etc/localtime:/etc/localtime:ro
     - /dev/rtc:/dev/rtc:ro
