---
version: '3.4'
services:
  storagenode:
    image: storjlabs/storagenode:${tag}
    container_name: storagenode 
    hostname: storagenode 
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev/rtc:/dev/rtc:ro
      - ${OPT}/storj/identity/storagenode:/app/identity
      - ${mnt}/storagenode:/app/config
    environment:
     - WALLET=${WALLET_ADDRESS}
     - EMAIL=${STORJ_EMAIL}
     - ADDRESS=${RPCADDRESS}:28967
     - BANDWIDTH=80TB
     - STORAGE=8TB
    ports:
      - 28967:28967
      - 14002:14002

  watchtower:
    image: storjlabs/watchtower
    container_name: watchtower
    hostname: watchtower
    environment:
      - WATCHTOWER_NOTIFICATION_EMAIL_SUBJECTTAG=${HOSTNAME}
      - WATCHTOWER_NOTIFICATIONS=email
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
      - WATCHTOWER_NOTIFICATION_EMAIL_FROM=${EMAIL_IBOX}
      - WATCHTOWER_NOTIFICATION_EMAIL_TO=${EMAIL}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=${DOMAIN}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${EMAIL}
      - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${EMAIL_PASS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --stop-timeout 300s --interval 21600

  openvpn:
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn
    hostname: openvpn
    ports:
     - "28967:1194/udp"
    restart: always
    volumes:
     - ${OPT}/openvpn:/etc/openvpn
     - /etc/localtime:/etc/localtime:ro
     - /dev/rtc:/dev/rtc:ro
